name: Build website

on:
  push:
    branches:
      - main
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # Step 3: Install dependencies
      - run: npm ci

      # Step 4: Run your npm script (replace 'build' with your script name)
      - run: npm run build

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          ssh-keyscan untilfalse.com >> ~/.ssh/known_hosts
          eval $(ssh-agent)
          ssh-add - <<< "${{ secrets.PRIVATE_KEY }}"

      # Step 3: Copy directory to VPS using rsync
      - name: Copy files to VPS
        run: |
          rsync -avz --delete ./public akash@untilfalse.com:/home/akash/apps/website/
