name: Build website

on:
  push:
    branches:
      - main
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # Step 3: Install dependencies
      - run: npm ci

      # Step 4: Run your npm script (replace 'build' with your script name)
      - run: npm run build

      

      # Step 5: Copy directory to VPS
      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "public"
          target: "/home/akash/apps/website/"
